use reqwest::Client;
use serde::{Deserialize, Serialize};
use std::env;
use tauri::AppHandle;
use tauri_plugin_store::StoreExt;
use crate::models::CaptionSegment;
use std::collections::HashMap;

#[derive(Serialize)]
struct GeminiRequest {
    contents: Vec<Content>,
    #[serde(rename = "generationConfig")]
    generation_config: GenerationConfig,
}

#[derive(Serialize)]
struct Content {
    parts: Vec<Part>,
}

#[derive(Serialize)]
struct Part {
    text: String,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct GenerationConfig {
    response_mime_type: String,
}

#[derive(Deserialize)]
struct GeminiResponse {
    candidates: Option<Vec<Candidate>>,
}

#[derive(Deserialize)]
struct Candidate {
    content: Option<CandidateContent>,
}

#[derive(Deserialize)]
struct CandidateContent {
    parts: Option<Vec<CandidatePart>>,
}

#[derive(Deserialize)]
struct CandidatePart {
    text: Option<String>,
}

#[derive(Deserialize, Debug)]
pub struct ImportantWord {
    pub word: String,
    pub importance: f32,
}

pub async fn extract_important_words_impl(
    app: AppHandle,
    mut segments: Vec<CaptionSegment>,
    language_code: String,
) -> Result<Vec<CaptionSegment>, String> {
    // Try to get API key from environment, fallback to Tauri store
    let api_key = env::var("GEMINI_API_KEY").or_else(|_| {
        let store = app.store("store.json").map_err(|e| e.to_string())?;
        store.get("gemini_api_key")
            .and_then(|v| v.as_str().map(|s| s.to_string()))
            .ok_or("GEMINI_API_KEY not found in environment variables or Tauri store".to_string())
    })?;

    // Concatenate all segments into a single transcript string
    let transcript = segments.iter()
        .map(|s| s.text.as_str())
        .collect::<Vec<&str>>()
        .join(" ");

    if transcript.trim().is_empty() {
        return Ok(segments);
    }

    let prompt = format!(
        "You are an AI tasked with analyzing a transcript to highlight important words for video captions.\n\
        Language: {}\n\
        Transcript: {}\n\n\
        Identify the most important words that carry the core meaning (verbs, nouns, key adjectives). Exclude stop words unless crucial.\n\
        Assign an importance score between 0.0 and 1.0 to each important word.\n\
        Return ONLY a JSON array of objects with keys 'word' and 'importance'.",
        language_code, transcript
    );

    let request_body = GeminiRequest {
        contents: vec![Content {
            parts: vec![Part { text: prompt }],
        }],
        generation_config: GenerationConfig {
            response_mime_type: "application/json".to_string(),
        },
    };

    let client = Client::new();
    let url = format!(
        "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key={}",
        api_key
    );

    let res = client.post(&url)
        .json(&request_body)
        .send()
        .await
        .map_err(|e| format!("Failed to call Gemini API: {}", e))?;

    if !res.status().is_success() {
        let err_text = res.text().await.unwrap_or_default();
        return Err(format!("Gemini API Error: {}", err_text));
    }

    let gemini_res: GeminiResponse = res.json().await
        .map_err(|e| format!("Failed to parse Gemini API response: {}", e))?;

    let response_text = gemini_res.candidates
        .and_then(|mut c| if !c.is_empty() { Some(c.remove(0)) } else { None })
        .and_then(|c| c.content)
        .and_then(|mut c| if let Some(p) = c.parts.as_mut() { if !p.is_empty() { Some(p.remove(0)) } else { None } } else { None })
        .and_then(|p| p.text)
        .ok_or("No text generated by Gemini")?;

    map_importance_from_gemini(segments, &response_text)
}

pub fn map_importance_from_gemini(mut segments: Vec<CaptionSegment>, response_text: &str) -> Result<Vec<CaptionSegment>, String> {
    let important_words: Vec<ImportantWord> = serde_json::from_str(response_text)
        .map_err(|e| format!("Failed to parse JSON from Gemini text: {}\nText: {}", e, response_text))?;

    // Create a lowercase map for easier matching, picking the highest importance for duplicates
    let mut importance_map: HashMap<String, f32> = HashMap::new();
    for iw in important_words {
        let lower = iw.word.to_lowercase();
        let entry = importance_map.entry(lower).or_insert(iw.importance);
        if iw.importance > *entry {
            *entry = iw.importance;
        }
    }

    // Map importance values back to the original segments
    for seg in &mut segments {
        for word in &mut seg.words {
            // Clean punctuation for matching
            let clean_word: String = word.word
                .to_lowercase()
                .chars()
                .filter(|c| c.is_alphanumeric())
                .collect();
                
            if let Some(&importance) = importance_map.get(&clean_word) {
                word.importance = importance;
            } else {
                word.importance = 0.0;
            }
        }
    }

    Ok(segments)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::models::{CaptionSegment, Word};

    #[test]
    fn test_map_importance_from_gemini() {
        let segments = vec![
            CaptionSegment {
                id: "1".to_string(),
                start: 0.0,
                end: 1.0,
                text: "Hello world!".to_string(),
                words: vec![
                    Word { word: "Hello".to_string(), start: 0.0, end: 0.5, importance: 0.0 },
                    Word { word: "world!".to_string(), start: 0.5, end: 1.0, importance: 0.0 },
                ],
            }
        ];

        let mock_response = r#"[
            {"word": "hello", "importance": 0.8},
            {"word": "world", "importance": 0.5}
        ]"#;

        let mapped = map_importance_from_gemini(segments, mock_response).unwrap();
        
        assert_eq!(mapped[0].words[0].importance, 0.8);
        assert_eq!(mapped[0].words[1].importance, 0.5); // should ignore the exclamation mark
    }
}

